default: &default
  adapter: postgresql
  encoding: unicode
  username: sample_app
  password: sample_app
  pool: 5
  host: localhost
  

development:
  <<: *default
  database: sample_app_development
  
  
test:
  <<: *default
  database: sample_app_test
  
  
production:
  <<: *default
  database: sample_app_production

